import Head from "next/head";
import React from "react";

const PageHead = () => {
  return (
    <Head>
      <title>Dream Vacation</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    </Head>
  );
};

export default PageHead;
